import { Router } from "express";

const router = Router();

function normalizeHeader(h: string): string {
  return String(h).toLowerCase().replace(/[\s().#_-]/g, "");
}

function getField(obj: Record<string, string>, ...keys: string[]): string {
  for (const k of keys) {
    const val = obj[normalizeHeader(k)];
    if (val !== undefined) return val;
  }
  return "";
}

// Returns true if column labels look auto-generated (e.g. "Column 1", "column1", "Col1", "A", "B")
function isAutoGeneratedCols(cols: string[]): boolean {
  if (cols.length === 0) return false;
  const autoPattern = /^(column\d+|col\d+|[a-e])$/i;
  const autoCount = cols.filter((c) => autoPattern.test(c.replace(/\s/g, ""))).length;
  return autoCount >= Math.ceil(cols.length / 2);
}

// Extract cell value as string
function cellVal(cell: any): string {
  if (!cell) return "";
  return String(cell.v ?? cell.f ?? "").trim();
}

// Build a patient object from a data row using column→key mapping
function buildPatient(obj: Record<string, string>) {
  return {
    name:      getField(obj, "name", "patientname", "patientname", "nam"),
    mobile:    getField(obj, "mobile", "mobilenumber", "mobileno", "phone", "contact", "mob"),
    age:       getField(obj, "age", "ageyrs", "ageyears", "ageinyr"),
    ageMonths: getField(obj, "agemo", "agemonths", "months", "ageinmonths"),
    weight:    getField(obj, "weight", "wt"),
    address:   getField(obj, "address", "city", "area", "addr"),
  };
}

router.get("/", async (req, res) => {
  const sheetId = req.query.sheetId as string;

  if (!sheetId || typeof sheetId !== "string") {
    res.status(400).json({ error: "sheetId query param is required" });
    return;
  }

  const url = `https://docs.google.com/spreadsheets/d/${encodeURIComponent(sheetId)}/gviz/tq?tqx=out:json`;

  let raw: string;
  try {
    const response = await fetch(url, {
      headers: { Accept: "text/javascript, application/json" },
    });
    if (!response.ok) {
      res.status(502).json({
        error: `Google returned HTTP ${response.status}. Check the Sheet ID and make sure it is shared as "Anyone with the link can view".`,
      });
      return;
    }
    raw = await response.text();
  } catch (err: any) {
    res.status(502).json({ error: `Could not reach Google Sheets: ${err.message}` });
    return;
  }

  // Strip the JSONP wrapper: google.visualization.Query.setResponse({...});
  const match = raw.match(/google\.visualization\.Query\.setResponse\(([\s\S]*)\);?\s*$/);
  if (!match) {
    res.status(502).json({
      error: 'Unexpected response from Google Sheets. Make sure the sheet is shared as "Anyone with the link can view".',
    });
    return;
  }

  let parsed: any;
  try {
    parsed = JSON.parse(match[1]);
  } catch {
    res.status(502).json({ error: "Could not parse Google Sheets response." });
    return;
  }

  if (parsed.status === "error") {
    const msg =
      parsed.errors?.[0]?.detailed_message ||
      parsed.errors?.[0]?.message ||
      "Unknown error from Google Sheets.";
    res.status(400).json({ error: msg });
    return;
  }

  const table = parsed.table;
  if (!table || !table.rows || table.rows.length === 0) {
    res.json({ patients: [] });
    return;
  }

  // Column labels from gviz
  let rawCols: string[] = (table.cols || []).map((c: any) =>
    normalizeHeader(c.label || c.id || "")
  );

  let dataRows: any[] = table.rows;

  // ── Detect Google Table / auto-generated columns ──────────────────────────
  // When using Google Sheets' Table feature, column labels become "Column 1",
  // "Column 2", etc. In that case, the first data row may contain the real
  // headers (NAME, MOBILE, AGE, WEIGHT, ADDRESS).
  if (isAutoGeneratedCols(rawCols) && dataRows.length > 0) {
    const firstRowVals = (dataRows[0].c || []).map((cell: any) =>
      normalizeHeader(cellVal(cell))
    );
    // If first row looks like headers (contains known words), use it
    const knownWords = ["name", "mobile", "age", "weight", "address", "phone", "contact"];
    const hasKnownHeaders = firstRowVals.some((v: string) =>
      knownWords.some((w) => v.includes(w))
    );
    if (hasKnownHeaders) {
      rawCols = firstRowVals;
      dataRows = dataRows.slice(1); // skip header row
    }
  }

  // ── Also skip any row where values match header patterns (sheet may have
  //    column labels repeated as first data row even without a Table) ─────────
  const knownHeaderValues = ["name", "mobile", "age", "weight", "address"];
  if (dataRows.length > 0) {
    const firstVals = (dataRows[0].c || []).map((cell: any) =>
      normalizeHeader(cellVal(cell))
    );
    const isHeaderRow = firstVals.filter((v: string) =>
      knownHeaderValues.some((w) => v === w || v.startsWith(w))
    ).length >= 2;
    if (isHeaderRow) {
      // Re-map columns using this header row
      rawCols = firstVals;
      dataRows = dataRows.slice(1);
    }
  }

  const patients = dataRows
    .map((row) => {
      const obj: Record<string, string> = {};
      (row.c || []).forEach((cell: any, i: number) => {
        obj[rawCols[i] ?? `col${i}`] = cellVal(cell);
      });
      return buildPatient(obj);
    })
    .filter((p) => p.name || p.mobile);

  res.json({ patients });
});

export default router;
